### ISSUE TITLE
File input

### ISSUE THREAD

**Issue by gyscos** [jedisct1/flowgger#20] opened 2017-06-21 22:14 UTC
I may have missed it, but I didn't find in the docs how to get input from a log file.

It would need to:
* Not read the whole file from the start, but seek to the end and read from there (like `tail -f`)
* Keep working if a logrotate service renames the log file and creates a new file with the previous name (flowgger should start reading the new file).

**Comment by rektide** [comment] 2017-11-16 21:17
Yes. This would let us use flowgger to replace many of our fluentd systemd.

To be able to read Docker logs, we use [in_tail](https://docs.fluentd.org/v0.14/articles/in_tail),  with a path of /var/lib/docker/containers/*/*-.json.log. Being able to "tail" (and as gyscos said resume tailing from a position) multiple files of input would be great. in_tail seems like an acceptable model.

For completeness, here's an example of one of our particular uses of in_tail to read multiple files:

```
<source>
  @type tail
  path /var/lib/docker/containers/*/*-json.log
  pos_file /var/lib/fluent/fluentd-docker.pos
  tag docker-tail.*
  format json_in_json
  time_key time
  time_format %Y-%m-%dT%H:%M:%S.%NZ
</source>
```

**Comment by Trojan295** [comment] 2018-02-11 15:06
Is someone working on this? I can try to implement it

**Comment by jedisct1** [comment] 2018-02-11 15:13
Hey @Trojan295, looks like nobody is, so if you can do it, that would be awesome!

**Comment by Trojan295** [comment] 2018-02-11 20:06
I'm thinking what about multiple file support and the wildcard @rektide posted.

For now I would drop defining multiple input files (as this goes more to general support for multiple inputs), but wildcard support is very useful.

I believe the expected behaviour in this case is: watch any existing files and files, which were created during runtime.

**Comment by Trojan295** [comment] 2018-03-06 23:21
@jedisct1, I've got a few questions, could you catch me on mail (visible in my profile)?

**Comment by kurojishi** [comment] 2019-09-17 09:51
already merged in

**Closed as completed by kurojishi** 2019-09-17 09:51 UTC
